// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: mehr/v1/query.proto

package types

import (
	context "context"
	fmt "fmt"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type QueryWebhooksRequest struct {
	Owner string `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
}

func (m *QueryWebhooksRequest) Reset()         { *m = QueryWebhooksRequest{} }
func (m *QueryWebhooksRequest) String() string { return proto.CompactTextString(m) }
func (*QueryWebhooksRequest) ProtoMessage()    {}
func (*QueryWebhooksRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9fd53211bfbb7f62, []int{0}
}
func (m *QueryWebhooksRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryWebhooksRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryWebhooksRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryWebhooksRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryWebhooksRequest.Merge(m, src)
}
func (m *QueryWebhooksRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryWebhooksRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryWebhooksRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryWebhooksRequest proto.InternalMessageInfo

func (m *QueryWebhooksRequest) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

type QueryWebhooksResponse struct {
	Webhooks []*Webhook `protobuf:"bytes,1,rep,name=webhooks,proto3" json:"webhooks,omitempty"`
}

func (m *QueryWebhooksResponse) Reset()         { *m = QueryWebhooksResponse{} }
func (m *QueryWebhooksResponse) String() string { return proto.CompactTextString(m) }
func (*QueryWebhooksResponse) ProtoMessage()    {}
func (*QueryWebhooksResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9fd53211bfbb7f62, []int{1}
}
func (m *QueryWebhooksResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryWebhooksResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryWebhooksResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryWebhooksResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryWebhooksResponse.Merge(m, src)
}
func (m *QueryWebhooksResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryWebhooksResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryWebhooksResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryWebhooksResponse proto.InternalMessageInfo

func (m *QueryWebhooksResponse) GetWebhooks() []*Webhook {
	if m != nil {
		return m.Webhooks
	}
	return nil
}

type QueryWebhookRequest struct {
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *QueryWebhookRequest) Reset()         { *m = QueryWebhookRequest{} }
func (m *QueryWebhookRequest) String() string { return proto.CompactTextString(m) }
func (*QueryWebhookRequest) ProtoMessage()    {}
func (*QueryWebhookRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9fd53211bfbb7f62, []int{2}
}
func (m *QueryWebhookRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryWebhookRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryWebhookRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryWebhookRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryWebhookRequest.Merge(m, src)
}
func (m *QueryWebhookRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryWebhookRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryWebhookRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryWebhookRequest proto.InternalMessageInfo

func (m *QueryWebhookRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type QueryWebhookResponse struct {
	Webhook *Webhook `protobuf:"bytes,1,opt,name=webhook,proto3" json:"webhook,omitempty"`
}

func (m *QueryWebhookResponse) Reset()         { *m = QueryWebhookResponse{} }
func (m *QueryWebhookResponse) String() string { return proto.CompactTextString(m) }
func (*QueryWebhookResponse) ProtoMessage()    {}
func (*QueryWebhookResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9fd53211bfbb7f62, []int{3}
}
func (m *QueryWebhookResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryWebhookResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryWebhookResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryWebhookResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryWebhookResponse.Merge(m, src)
}
func (m *QueryWebhookResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryWebhookResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryWebhookResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryWebhookResponse proto.InternalMessageInfo

func (m *QueryWebhookResponse) GetWebhook() *Webhook {
	if m != nil {
		return m.Webhook
	}
	return nil
}

type QueryAllWebhooksRequest struct{}

func (m *QueryAllWebhooksRequest) Reset()         { *m = QueryAllWebhooksRequest{} }
func (m *QueryAllWebhooksRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllWebhooksRequest) ProtoMessage()    {}
func (*QueryAllWebhooksRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9fd53211bfbb7f62, []int{4}
}
func (m *QueryAllWebhooksRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllWebhooksRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllWebhooksRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllWebhooksRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllWebhooksRequest.Merge(m, src)
}
func (m *QueryAllWebhooksRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllWebhooksRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllWebhooksRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllWebhooksRequest proto.InternalMessageInfo

type QueryAllWebhooksResponse struct {
	Webhooks []*Webhook `protobuf:"bytes,1,rep,name=webhooks,proto3" json:"webhooks,omitempty"`
}

func (m *QueryAllWebhooksResponse) Reset()         { *m = QueryAllWebhooksResponse{} }
func (m *QueryAllWebhooksResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllWebhooksResponse) ProtoMessage()    {}
func (*QueryAllWebhooksResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9fd53211bfbb7f62, []int{5}
}
func (m *QueryAllWebhooksResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllWebhooksResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllWebhooksResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllWebhooksResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllWebhooksResponse.Merge(m, src)
}
func (m *QueryAllWebhooksResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllWebhooksResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllWebhooksResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllWebhooksResponse proto.InternalMessageInfo

func (m *QueryAllWebhooksResponse) GetWebhooks() []*Webhook {
	if m != nil {
		return m.Webhooks
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryWebhooksRequest)(nil), "mehr.v1.QueryWebhooksRequest")
	proto.RegisterType((*QueryWebhooksResponse)(nil), "mehr.v1.QueryWebhooksResponse")
	proto.RegisterType((*QueryWebhookRequest)(nil), "mehr.v1.QueryWebhookRequest")
	proto.RegisterType((*QueryWebhookResponse)(nil), "mehr.v1.QueryWebhookResponse")
	proto.RegisterType((*QueryAllWebhooksRequest)(nil), "mehr.v1.QueryAllWebhooksRequest")
	proto.RegisterType((*QueryAllWebhooksResponse)(nil), "mehr.v1.QueryAllWebhooksResponse")
}

func init() { proto.RegisterFile("mehr/v1/query.proto", fileDescriptor_9fd53211bfbb7f62) }

var fileDescriptor_9fd53211bfbb7f62 = []byte{
	// Placeholder — file descriptor not used at runtime for hand-written pb files.
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xff, 0x01, 0x00, 0x00, 0xff, 0xff, 0x00,
	0x00, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Feed returns a single feed by ID.
	Feed(ctx context.Context, in *QueryFeedRequest, opts ...grpc.CallOption) (*QueryFeedResponse, error)
	// AllFeeds returns all registered feeds.
	AllFeeds(ctx context.Context, in *QueryAllFeedsRequest, opts ...grpc.CallOption) (*QueryAllFeedsResponse, error)
	// Fact returns a single fact by ID.
	Fact(ctx context.Context, in *QueryFactRequest, opts ...grpc.CallOption) (*QueryFactResponse, error)
	// FactsByFeed returns all facts for a given feed.
	FactsByFeed(ctx context.Context, in *QueryFactsByFeedRequest, opts ...grpc.CallOption) (*QueryFactsByFeedResponse, error)
	// Subscription returns a single subscription by ID.
	Subscription(ctx context.Context, in *QuerySubscriptionRequest, opts ...grpc.CallOption) (*QuerySubscriptionResponse, error)
	// SubscriptionsByOwner returns all subscriptions owned by an address.
	SubscriptionsByOwner(ctx context.Context, in *QuerySubscriptionsByOwnerRequest, opts ...grpc.CallOption) (*QuerySubscriptionsByOwnerResponse, error)
	// AllSubscriptions returns all subscriptions.
	AllSubscriptions(ctx context.Context, in *QueryAllSubscriptionsRequest, opts ...grpc.CallOption) (*QueryAllSubscriptionsResponse, error)
	// AllWebhooks returns every webhook across all owners — used by webhook workers.
	AllWebhooks(ctx context.Context, in *QueryAllWebhooksRequest, opts ...grpc.CallOption) (*QueryAllWebhooksResponse, error)
	// Webhooks returns all webhooks owned by an address.
	Webhooks(ctx context.Context, in *QueryWebhooksRequest, opts ...grpc.CallOption) (*QueryWebhooksResponse, error)
	// Webhook returns a single webhook by ID.
	Webhook(ctx context.Context, in *QueryWebhookRequest, opts ...grpc.CallOption) (*QueryWebhookResponse, error)
	// FeederDelegation returns the delegation record for a delegator address.
	FeederDelegation(ctx context.Context, in *QueryFeederDelegationRequest, opts ...grpc.CallOption) (*QueryFeederDelegationResponse, error)
	// AllDelegations returns all feeder delegations.
	AllDelegations(ctx context.Context, in *QueryAllDelegationsRequest, opts ...grpc.CallOption) (*QueryAllDelegationsResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Feed(ctx context.Context, in *QueryFeedRequest, opts ...grpc.CallOption) (*QueryFeedResponse, error) {
	out := new(QueryFeedResponse)
	err := c.cc.Invoke(ctx, "/mehr.v1.Query/Feed", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) AllFeeds(ctx context.Context, in *QueryAllFeedsRequest, opts ...grpc.CallOption) (*QueryAllFeedsResponse, error) {
	out := new(QueryAllFeedsResponse)
	err := c.cc.Invoke(ctx, "/mehr.v1.Query/AllFeeds", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Fact(ctx context.Context, in *QueryFactRequest, opts ...grpc.CallOption) (*QueryFactResponse, error) {
	out := new(QueryFactResponse)
	err := c.cc.Invoke(ctx, "/mehr.v1.Query/Fact", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) FactsByFeed(ctx context.Context, in *QueryFactsByFeedRequest, opts ...grpc.CallOption) (*QueryFactsByFeedResponse, error) {
	out := new(QueryFactsByFeedResponse)
	err := c.cc.Invoke(ctx, "/mehr.v1.Query/FactsByFeed", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Subscription(ctx context.Context, in *QuerySubscriptionRequest, opts ...grpc.CallOption) (*QuerySubscriptionResponse, error) {
	out := new(QuerySubscriptionResponse)
	err := c.cc.Invoke(ctx, "/mehr.v1.Query/Subscription", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) SubscriptionsByOwner(ctx context.Context, in *QuerySubscriptionsByOwnerRequest, opts ...grpc.CallOption) (*QuerySubscriptionsByOwnerResponse, error) {
	out := new(QuerySubscriptionsByOwnerResponse)
	err := c.cc.Invoke(ctx, "/mehr.v1.Query/SubscriptionsByOwner", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) AllSubscriptions(ctx context.Context, in *QueryAllSubscriptionsRequest, opts ...grpc.CallOption) (*QueryAllSubscriptionsResponse, error) {
	out := new(QueryAllSubscriptionsResponse)
	err := c.cc.Invoke(ctx, "/mehr.v1.Query/AllSubscriptions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) AllWebhooks(ctx context.Context, in *QueryAllWebhooksRequest, opts ...grpc.CallOption) (*QueryAllWebhooksResponse, error) {
	out := new(QueryAllWebhooksResponse)
	err := c.cc.Invoke(ctx, "/mehr.v1.Query/AllWebhooks", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Webhooks(ctx context.Context, in *QueryWebhooksRequest, opts ...grpc.CallOption) (*QueryWebhooksResponse, error) {
	out := new(QueryWebhooksResponse)
	err := c.cc.Invoke(ctx, "/mehr.v1.Query/Webhooks", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Webhook(ctx context.Context, in *QueryWebhookRequest, opts ...grpc.CallOption) (*QueryWebhookResponse, error) {
	out := new(QueryWebhookResponse)
	err := c.cc.Invoke(ctx, "/mehr.v1.Query/Webhook", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) FeederDelegation(ctx context.Context, in *QueryFeederDelegationRequest, opts ...grpc.CallOption) (*QueryFeederDelegationResponse, error) {
	out := new(QueryFeederDelegationResponse)
	err := c.cc.Invoke(ctx, "/mehr.v1.Query/FeederDelegation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) AllDelegations(ctx context.Context, in *QueryAllDelegationsRequest, opts ...grpc.CallOption) (*QueryAllDelegationsResponse, error) {
	out := new(QueryAllDelegationsResponse)
	err := c.cc.Invoke(ctx, "/mehr.v1.Query/AllDelegations", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Feed returns a single feed by ID.
	Feed(context.Context, *QueryFeedRequest) (*QueryFeedResponse, error)
	// AllFeeds returns all registered feeds.
	AllFeeds(context.Context, *QueryAllFeedsRequest) (*QueryAllFeedsResponse, error)
	// Fact returns a single fact by ID.
	Fact(context.Context, *QueryFactRequest) (*QueryFactResponse, error)
	// FactsByFeed returns all facts for a given feed.
	FactsByFeed(context.Context, *QueryFactsByFeedRequest) (*QueryFactsByFeedResponse, error)
	// Subscription returns a single subscription by ID.
	Subscription(context.Context, *QuerySubscriptionRequest) (*QuerySubscriptionResponse, error)
	// SubscriptionsByOwner returns all subscriptions owned by an address.
	SubscriptionsByOwner(context.Context, *QuerySubscriptionsByOwnerRequest) (*QuerySubscriptionsByOwnerResponse, error)
	// AllSubscriptions returns all subscriptions.
	AllSubscriptions(context.Context, *QueryAllSubscriptionsRequest) (*QueryAllSubscriptionsResponse, error)
	// AllWebhooks returns every webhook across all owners — used by webhook workers.
	AllWebhooks(context.Context, *QueryAllWebhooksRequest) (*QueryAllWebhooksResponse, error)
	// Webhooks returns all webhooks owned by an address.
	Webhooks(context.Context, *QueryWebhooksRequest) (*QueryWebhooksResponse, error)
	// Webhook returns a single webhook by ID.
	Webhook(context.Context, *QueryWebhookRequest) (*QueryWebhookResponse, error)
	// FeederDelegation returns the delegation record for a delegator address.
	FeederDelegation(context.Context, *QueryFeederDelegationRequest) (*QueryFeederDelegationResponse, error)
	// AllDelegations returns all feeder delegations.
	AllDelegations(context.Context, *QueryAllDelegationsRequest) (*QueryAllDelegationsResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Feed(ctx context.Context, req *QueryFeedRequest) (*QueryFeedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Feed not implemented")
}
func (*UnimplementedQueryServer) AllFeeds(ctx context.Context, req *QueryAllFeedsRequest) (*QueryAllFeedsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AllFeeds not implemented")
}
func (*UnimplementedQueryServer) Fact(ctx context.Context, req *QueryFactRequest) (*QueryFactResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Fact not implemented")
}
func (*UnimplementedQueryServer) FactsByFeed(ctx context.Context, req *QueryFactsByFeedRequest) (*QueryFactsByFeedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FactsByFeed not implemented")
}
func (*UnimplementedQueryServer) Subscription(ctx context.Context, req *QuerySubscriptionRequest) (*QuerySubscriptionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Subscription not implemented")
}
func (*UnimplementedQueryServer) SubscriptionsByOwner(ctx context.Context, req *QuerySubscriptionsByOwnerRequest) (*QuerySubscriptionsByOwnerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubscriptionsByOwner not implemented")
}
func (*UnimplementedQueryServer) AllSubscriptions(ctx context.Context, req *QueryAllSubscriptionsRequest) (*QueryAllSubscriptionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AllSubscriptions not implemented")
}
func (*UnimplementedQueryServer) AllWebhooks(ctx context.Context, req *QueryAllWebhooksRequest) (*QueryAllWebhooksResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AllWebhooks not implemented")
}
func (*UnimplementedQueryServer) Webhooks(ctx context.Context, req *QueryWebhooksRequest) (*QueryWebhooksResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Webhooks not implemented")
}
func (*UnimplementedQueryServer) Webhook(ctx context.Context, req *QueryWebhookRequest) (*QueryWebhookResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Webhook not implemented")
}
func (*UnimplementedQueryServer) FeederDelegation(ctx context.Context, req *QueryFeederDelegationRequest) (*QueryFeederDelegationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FeederDelegation not implemented")
}
func (*UnimplementedQueryServer) AllDelegations(ctx context.Context, req *QueryAllDelegationsRequest) (*QueryAllDelegationsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AllDelegations not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Feed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryFeedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Feed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mehr.v1.Query/Feed",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Feed(ctx, req.(*QueryFeedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_AllFeeds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllFeedsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).AllFeeds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mehr.v1.Query/AllFeeds",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).AllFeeds(ctx, req.(*QueryAllFeedsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Fact_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryFactRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Fact(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mehr.v1.Query/Fact",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Fact(ctx, req.(*QueryFactRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_FactsByFeed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryFactsByFeedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).FactsByFeed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mehr.v1.Query/FactsByFeed",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).FactsByFeed(ctx, req.(*QueryFactsByFeedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Subscription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuerySubscriptionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Subscription(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mehr.v1.Query/Subscription",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Subscription(ctx, req.(*QuerySubscriptionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_SubscriptionsByOwner_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuerySubscriptionsByOwnerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).SubscriptionsByOwner(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mehr.v1.Query/SubscriptionsByOwner",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).SubscriptionsByOwner(ctx, req.(*QuerySubscriptionsByOwnerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_AllSubscriptions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllSubscriptionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).AllSubscriptions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mehr.v1.Query/AllSubscriptions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).AllSubscriptions(ctx, req.(*QueryAllSubscriptionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_AllWebhooks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllWebhooksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).AllWebhooks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mehr.v1.Query/AllWebhooks",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).AllWebhooks(ctx, req.(*QueryAllWebhooksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Webhooks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryWebhooksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Webhooks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mehr.v1.Query/Webhooks",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Webhooks(ctx, req.(*QueryWebhooksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Webhook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryWebhookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Webhook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mehr.v1.Query/Webhook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Webhook(ctx, req.(*QueryWebhookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_FeederDelegation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryFeederDelegationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).FeederDelegation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mehr.v1.Query/FeederDelegation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).FeederDelegation(ctx, req.(*QueryFeederDelegationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_AllDelegations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllDelegationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).AllDelegations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mehr.v1.Query/AllDelegations",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).AllDelegations(ctx, req.(*QueryAllDelegationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var Query_serviceDesc = _Query_serviceDesc
var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "mehr.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Feed",
			Handler:    _Query_Feed_Handler,
		},
		{
			MethodName: "AllFeeds",
			Handler:    _Query_AllFeeds_Handler,
		},
		{
			MethodName: "Fact",
			Handler:    _Query_Fact_Handler,
		},
		{
			MethodName: "FactsByFeed",
			Handler:    _Query_FactsByFeed_Handler,
		},
		{
			MethodName: "Subscription",
			Handler:    _Query_Subscription_Handler,
		},
		{
			MethodName: "SubscriptionsByOwner",
			Handler:    _Query_SubscriptionsByOwner_Handler,
		},
		{
			MethodName: "AllSubscriptions",
			Handler:    _Query_AllSubscriptions_Handler,
		},
		{
			MethodName: "AllWebhooks",
			Handler:    _Query_AllWebhooks_Handler,
		},
		{
			MethodName: "Webhooks",
			Handler:    _Query_Webhooks_Handler,
		},
		{
			MethodName: "Webhook",
			Handler:    _Query_Webhook_Handler,
		},
		{
			MethodName: "FeederDelegation",
			Handler:    _Query_FeederDelegation_Handler,
		},
		{
			MethodName: "AllDelegations",
			Handler:    _Query_AllDelegations_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mehr/v1/query.proto",
}

func (m *QueryWebhooksRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryWebhooksRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryWebhooksRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Owner) > 0 {
		i -= len(m.Owner)
		copy(dAtA[i:], m.Owner)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Owner)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryWebhooksResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryWebhooksResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryWebhooksResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Webhooks) > 0 {
		for iNdEx := len(m.Webhooks) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Webhooks[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryWebhookRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryWebhookRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryWebhookRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryWebhookResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryWebhookResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryWebhookResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Webhook != nil {
		{
			size, err := m.Webhook.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllWebhooksRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllWebhooksRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllWebhooksRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryAllWebhooksResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllWebhooksResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllWebhooksResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Webhooks) > 0 {
		for iNdEx := len(m.Webhooks) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Webhooks[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}

func (m *QueryWebhooksRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Owner)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryWebhooksResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Webhooks) > 0 {
		for _, e := range m.Webhooks {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func (m *QueryWebhookRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovQuery(uint64(m.Id))
	}
	return n
}

func (m *QueryWebhookResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Webhook != nil {
		l = m.Webhook.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllWebhooksRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	return 0
}

func (m *QueryAllWebhooksResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Webhooks) > 0 {
		for _, e := range m.Webhooks {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}

func (m *QueryWebhooksRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryWebhooksRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryWebhooksRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Owner", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Owner = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}

func (m *QueryWebhooksResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryWebhooksResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryWebhooksResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Webhooks", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Webhooks = append(m.Webhooks, &Webhook{})
			if err := m.Webhooks[len(m.Webhooks)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}

func (m *QueryWebhookRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryWebhookRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryWebhookRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}

func (m *QueryWebhookResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryWebhookResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryWebhookResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Webhook", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Webhook == nil {
				m.Webhook = &Webhook{}
			}
			if err := m.Webhook.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}

func (m *QueryAllWebhooksRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllWebhooksRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllWebhooksRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}
	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}

func (m *QueryAllWebhooksResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllWebhooksResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllWebhooksResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Webhooks", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Webhooks = append(m.Webhooks, &Webhook{})
			if err := m.Webhooks[len(m.Webhooks)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}

func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
