// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: mehr/v1/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MsgCreateWatch struct {
	Creator string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Network string `protobuf:"bytes,2,opt,name=network,proto3" json:"network,omitempty"`
	Address string `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	Label   string `protobuf:"bytes,4,opt,name=label,proto3" json:"label,omitempty"`
}

func (m *MsgCreateWatch) Reset()         { *m = MsgCreateWatch{} }
func (m *MsgCreateWatch) String() string { return proto.CompactTextString(m) }
func (*MsgCreateWatch) ProtoMessage()    {}
func (*MsgCreateWatch) Descriptor() ([]byte, []int) {
	return fileDescriptor_28a84c52c4df2031, []int{0}
}
func (m *MsgCreateWatch) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreateWatch) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreateWatch.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreateWatch) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateWatch.Merge(m, src)
}
func (m *MsgCreateWatch) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreateWatch) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateWatch.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateWatch proto.InternalMessageInfo

func (m *MsgCreateWatch) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgCreateWatch) GetNetwork() string {
	if m != nil {
		return m.Network
	}
	return ""
}

func (m *MsgCreateWatch) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *MsgCreateWatch) GetLabel() string {
	if m != nil {
		return m.Label
	}
	return ""
}

type MsgCreateWatchResponse struct {
	Watch *Watch `protobuf:"bytes,1,opt,name=watch,proto3" json:"watch,omitempty"`
}

func (m *MsgCreateWatchResponse) Reset()         { *m = MsgCreateWatchResponse{} }
func (m *MsgCreateWatchResponse) String() string { return proto.CompactTextString(m) }
func (*MsgCreateWatchResponse) ProtoMessage()    {}
func (*MsgCreateWatchResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_28a84c52c4df2031, []int{1}
}
func (m *MsgCreateWatchResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreateWatchResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreateWatchResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreateWatchResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateWatchResponse.Merge(m, src)
}
func (m *MsgCreateWatchResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreateWatchResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateWatchResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateWatchResponse proto.InternalMessageInfo

func (m *MsgCreateWatchResponse) GetWatch() *Watch {
	if m != nil {
		return m.Watch
	}
	return nil
}

type MsgDeleteWatch struct {
	Creator string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	WatchId uint64 `protobuf:"varint,2,opt,name=watch_id,json=watchId,proto3" json:"watch_id,omitempty"`
}

func (m *MsgDeleteWatch) Reset()         { *m = MsgDeleteWatch{} }
func (m *MsgDeleteWatch) String() string { return proto.CompactTextString(m) }
func (*MsgDeleteWatch) ProtoMessage()    {}
func (*MsgDeleteWatch) Descriptor() ([]byte, []int) {
	return fileDescriptor_28a84c52c4df2031, []int{2}
}
func (m *MsgDeleteWatch) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgDeleteWatch) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgDeleteWatch.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgDeleteWatch) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgDeleteWatch.Merge(m, src)
}
func (m *MsgDeleteWatch) XXX_Size() int {
	return m.Size()
}
func (m *MsgDeleteWatch) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgDeleteWatch.DiscardUnknown(m)
}

var xxx_messageInfo_MsgDeleteWatch proto.InternalMessageInfo

func (m *MsgDeleteWatch) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgDeleteWatch) GetWatchId() uint64 {
	if m != nil {
		return m.WatchId
	}
	return 0
}

type MsgDeleteWatchResponse struct {
}

func (m *MsgDeleteWatchResponse) Reset()         { *m = MsgDeleteWatchResponse{} }
func (m *MsgDeleteWatchResponse) String() string { return proto.CompactTextString(m) }
func (*MsgDeleteWatchResponse) ProtoMessage()    {}
func (*MsgDeleteWatchResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_28a84c52c4df2031, []int{3}
}
func (m *MsgDeleteWatchResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgDeleteWatchResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgDeleteWatchResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgDeleteWatchResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgDeleteWatchResponse.Merge(m, src)
}
func (m *MsgDeleteWatchResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgDeleteWatchResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgDeleteWatchResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgDeleteWatchResponse proto.InternalMessageInfo

type MsgCreateWebhook struct {
	Creator    string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Url        string `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	SecretHash string `protobuf:"bytes,3,opt,name=secret_hash,json=secretHash,proto3" json:"secret_hash,omitempty"`
}

func (m *MsgCreateWebhook) Reset()         { *m = MsgCreateWebhook{} }
func (m *MsgCreateWebhook) String() string { return proto.CompactTextString(m) }
func (*MsgCreateWebhook) ProtoMessage()    {}
func (*MsgCreateWebhook) Descriptor() ([]byte, []int) {
	return fileDescriptor_28a84c52c4df2031, []int{4}
}
func (m *MsgCreateWebhook) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreateWebhook) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreateWebhook.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreateWebhook) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateWebhook.Merge(m, src)
}
func (m *MsgCreateWebhook) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreateWebhook) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateWebhook.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateWebhook proto.InternalMessageInfo

func (m *MsgCreateWebhook) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgCreateWebhook) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *MsgCreateWebhook) GetSecretHash() string {
	if m != nil {
		return m.SecretHash
	}
	return ""
}

type MsgCreateWebhookResponse struct {
	Webhook *Webhook `protobuf:"bytes,1,opt,name=webhook,proto3" json:"webhook,omitempty"`
}

func (m *MsgCreateWebhookResponse) Reset()         { *m = MsgCreateWebhookResponse{} }
func (m *MsgCreateWebhookResponse) String() string { return proto.CompactTextString(m) }
func (*MsgCreateWebhookResponse) ProtoMessage()    {}
func (*MsgCreateWebhookResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_28a84c52c4df2031, []int{5}
}
func (m *MsgCreateWebhookResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreateWebhookResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreateWebhookResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreateWebhookResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateWebhookResponse.Merge(m, src)
}
func (m *MsgCreateWebhookResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreateWebhookResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateWebhookResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateWebhookResponse proto.InternalMessageInfo

func (m *MsgCreateWebhookResponse) GetWebhook() *Webhook {
	if m != nil {
		return m.Webhook
	}
	return nil
}

type MsgDeleteWebhook struct {
	Creator   string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	WebhookId uint64 `protobuf:"varint,2,opt,name=webhook_id,json=webhookId,proto3" json:"webhook_id,omitempty"`
}

func (m *MsgDeleteWebhook) Reset()         { *m = MsgDeleteWebhook{} }
func (m *MsgDeleteWebhook) String() string { return proto.CompactTextString(m) }
func (*MsgDeleteWebhook) ProtoMessage()    {}
func (*MsgDeleteWebhook) Descriptor() ([]byte, []int) {
	return fileDescriptor_28a84c52c4df2031, []int{6}
}
func (m *MsgDeleteWebhook) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgDeleteWebhook) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgDeleteWebhook.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgDeleteWebhook) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgDeleteWebhook.Merge(m, src)
}
func (m *MsgDeleteWebhook) XXX_Size() int {
	return m.Size()
}
func (m *MsgDeleteWebhook) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgDeleteWebhook.DiscardUnknown(m)
}

var xxx_messageInfo_MsgDeleteWebhook proto.InternalMessageInfo

func (m *MsgDeleteWebhook) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgDeleteWebhook) GetWebhookId() uint64 {
	if m != nil {
		return m.WebhookId
	}
	return 0
}

type MsgDeleteWebhookResponse struct {
}

func (m *MsgDeleteWebhookResponse) Reset()         { *m = MsgDeleteWebhookResponse{} }
func (m *MsgDeleteWebhookResponse) String() string { return proto.CompactTextString(m) }
func (*MsgDeleteWebhookResponse) ProtoMessage()    {}
func (*MsgDeleteWebhookResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_28a84c52c4df2031, []int{7}
}
func (m *MsgDeleteWebhookResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgDeleteWebhookResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgDeleteWebhookResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgDeleteWebhookResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgDeleteWebhookResponse.Merge(m, src)
}
func (m *MsgDeleteWebhookResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgDeleteWebhookResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgDeleteWebhookResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgDeleteWebhookResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgCreateWatch)(nil), "mehr.v1.MsgCreateWatch")
	proto.RegisterType((*MsgCreateWatchResponse)(nil), "mehr.v1.MsgCreateWatchResponse")
	proto.RegisterType((*MsgDeleteWatch)(nil), "mehr.v1.MsgDeleteWatch")
	proto.RegisterType((*MsgDeleteWatchResponse)(nil), "mehr.v1.MsgDeleteWatchResponse")
	proto.RegisterType((*MsgCreateWebhook)(nil), "mehr.v1.MsgCreateWebhook")
	proto.RegisterType((*MsgCreateWebhookResponse)(nil), "mehr.v1.MsgCreateWebhookResponse")
	proto.RegisterType((*MsgDeleteWebhook)(nil), "mehr.v1.MsgDeleteWebhook")
	proto.RegisterType((*MsgDeleteWebhookResponse)(nil), "mehr.v1.MsgDeleteWebhookResponse")
}

func init() { proto.RegisterFile("mehr/v1/tx.proto", fileDescriptor_28a84c52c4df2031) }

var fileDescriptor_28a84c52c4df2031 = []byte{
	// 476 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x53, 0xcb, 0x6e, 0xd3, 0x40,
	0x14, 0x8d, 0x9b, 0x06, 0xd3, 0x6b, 0xa8, 0x2c, 0x83, 0xa8, 0x63, 0x09, 0x17, 0x2c, 0x84, 0x50,
	0x16, 0xb6, 0x5a, 0x76, 0x2c, 0x10, 0x02, 0x44, 0x61, 0x91, 0x4d, 0x58, 0x20, 0xd8, 0x54, 0x7e,
	0x0c, 0x76, 0x55, 0xdb, 0x13, 0xcd, 0x38, 0x4d, 0xd9, 0xa1, 0x7e, 0x01, 0x9f, 0x92, 0x0f, 0xe0,
	0x03, 0x58, 0x66, 0xc9, 0x12, 0x25, 0x8b, 0xfc, 0x06, 0x9a, 0x87, 0x1d, 0x3b, 0x38, 0x64, 0xe7,
	0x7b, 0xce, 0x9d, 0x33, 0xe7, 0x9e, 0xeb, 0x01, 0x3d, 0x43, 0x09, 0xf1, 0xae, 0x4e, 0xbc, 0xe2,
	0xda, 0x1d, 0x13, 0x5c, 0x60, 0x43, 0x65, 0x88, 0x7b, 0x75, 0x62, 0x1d, 0x85, 0x98, 0x66, 0x98,
	0x7a, 0x19, 0x8d, 0x59, 0x43, 0x46, 0x63, 0xd1, 0x61, 0xdd, 0xab, 0xce, 0x7c, 0x1b, 0x23, 0x2a,
	0x40, 0xe7, 0x46, 0x81, 0xc3, 0x21, 0x8d, 0xdf, 0x10, 0xe4, 0x17, 0xe8, 0x93, 0x5f, 0x84, 0x89,
	0x61, 0x82, 0x1a, 0xb2, 0x12, 0x13, 0x53, 0x79, 0xa4, 0x3c, 0x3b, 0x18, 0x95, 0x25, 0x63, 0x72,
	0x54, 0x4c, 0x31, 0xb9, 0x34, 0xf7, 0x04, 0x23, 0x4b, 0xc6, 0xf8, 0x51, 0x44, 0x10, 0xa5, 0x66,
	0x57, 0x30, 0xb2, 0x34, 0xee, 0x43, 0x2f, 0xf5, 0x03, 0x94, 0x9a, 0xfb, 0x1c, 0x17, 0xc5, 0x8b,
	0x3b, 0x37, 0xab, 0xd9, 0xa0, 0xd4, 0x75, 0x5e, 0xc2, 0x83, 0xa6, 0x87, 0x11, 0xa2, 0x63, 0x9c,
	0x53, 0x64, 0x3c, 0x81, 0xde, 0x94, 0x01, 0xdc, 0x89, 0x76, 0x7a, 0xe8, 0xca, 0x29, 0x5d, 0xd1,
	0x26, 0x48, 0xe7, 0x23, 0x9f, 0xe1, 0x2d, 0x4a, 0xd1, 0xee, 0x19, 0xfa, 0x70, 0x9b, 0x1f, 0x3a,
	0xbf, 0x88, 0xf8, 0x10, 0xfb, 0x23, 0x95, 0xd7, 0x1f, 0xa2, 0x0d, 0x53, 0x26, 0x37, 0x55, 0x13,
	0x2d, 0x4d, 0x39, 0x19, 0xe8, 0x6b, 0xbb, 0x28, 0x48, 0x30, 0xbe, 0xfc, 0xcf, 0x85, 0x3a, 0x74,
	0x27, 0x24, 0x95, 0x81, 0xb1, 0x4f, 0xe3, 0x18, 0x34, 0x8a, 0x42, 0x82, 0x8a, 0xf3, 0xc4, 0xa7,
	0x89, 0x0c, 0x0c, 0x04, 0xf4, 0xde, 0xa7, 0xc9, 0x86, 0x91, 0x77, 0x60, 0x6e, 0x5e, 0x57, 0xe5,
	0x33, 0x00, 0x75, 0x2a, 0x20, 0x99, 0x90, 0xbe, 0x4e, 0x48, 0xb6, 0x96, 0x0d, 0xce, 0x67, 0x6e,
	0x5b, 0x0e, 0xb4, 0xd3, 0xf6, 0x43, 0x00, 0x79, 0x70, 0x9d, 0xd4, 0x81, 0x44, 0xfe, 0xc9, 0xca,
	0xe2, 0x16, 0x1b, 0xd2, 0xa5, 0xc5, 0xd3, 0x9f, 0x7b, 0xd0, 0x1d, 0xd2, 0xd8, 0x38, 0x03, 0xad,
	0xfe, 0x97, 0x1d, 0x55, 0x46, 0x9b, 0xab, 0xb7, 0x8e, 0xb7, 0x10, 0xd5, 0xcc, 0x67, 0xa0, 0xd5,
	0x57, 0xdd, 0x10, 0xaa, 0x11, 0x4d, 0xa1, 0x96, 0x3d, 0x1a, 0x43, 0xb8, 0xdb, 0x5c, 0x62, 0xbf,
	0xe5, 0x6a, 0x41, 0x59, 0x8f, 0xb7, 0x52, 0x75, 0xb9, 0x66, 0xb8, 0xfd, 0x16, 0x03, 0x6d, 0x72,
	0xad, 0xb9, 0x59, 0xbd, 0xef, 0xab, 0xd9, 0x40, 0x79, 0xfd, 0xea, 0xd7, 0xc2, 0x56, 0xe6, 0x0b,
	0x5b, 0xf9, 0xb3, 0xb0, 0x95, 0x1f, 0x4b, 0xbb, 0x33, 0x5f, 0xda, 0x9d, 0xdf, 0x4b, 0xbb, 0xf3,
	0xe5, 0x69, 0x7c, 0x51, 0x24, 0x93, 0xc0, 0x0d, 0x71, 0xe6, 0x31, 0xb5, 0xaf, 0x93, 0x3c, 0xa2,
	0x5e, 0x8e, 0x23, 0xe4, 0x5d, 0x73, 0x40, 0x3c, 0xf4, 0xe0, 0x16, 0x7f, 0xe9, 0xcf, 0xff, 0x06,
	0x00, 0x00, 0xff, 0xff, 0x1f, 0x3b, 0xc1, 0x37, 0x34, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	// CreateWatch registers a new EVM address watch.
	CreateWatch(ctx context.Context, in *MsgCreateWatch, opts ...grpc.CallOption) (*MsgCreateWatchResponse, error)
	// DeleteWatch removes an existing watch (must be owner).
	DeleteWatch(ctx context.Context, in *MsgDeleteWatch, opts ...grpc.CallOption) (*MsgDeleteWatchResponse, error)
	// CreateWebhook registers a new webhook delivery endpoint.
	CreateWebhook(ctx context.Context, in *MsgCreateWebhook, opts ...grpc.CallOption) (*MsgCreateWebhookResponse, error)
	// DeleteWebhook removes an existing webhook (must be owner).
	DeleteWebhook(ctx context.Context, in *MsgDeleteWebhook, opts ...grpc.CallOption) (*MsgDeleteWebhookResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) CreateWatch(ctx context.Context, in *MsgCreateWatch, opts ...grpc.CallOption) (*MsgCreateWatchResponse, error) {
	out := new(MsgCreateWatchResponse)
	err := c.cc.Invoke(ctx, "/mehr.v1.Msg/CreateWatch", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) DeleteWatch(ctx context.Context, in *MsgDeleteWatch, opts ...grpc.CallOption) (*MsgDeleteWatchResponse, error) {
	out := new(MsgDeleteWatchResponse)
	err := c.cc.Invoke(ctx, "/mehr.v1.Msg/DeleteWatch", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) CreateWebhook(ctx context.Context, in *MsgCreateWebhook, opts ...grpc.CallOption) (*MsgCreateWebhookResponse, error) {
	out := new(MsgCreateWebhookResponse)
	err := c.cc.Invoke(ctx, "/mehr.v1.Msg/CreateWebhook", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) DeleteWebhook(ctx context.Context, in *MsgDeleteWebhook, opts ...grpc.CallOption) (*MsgDeleteWebhookResponse, error) {
	out := new(MsgDeleteWebhookResponse)
	err := c.cc.Invoke(ctx, "/mehr.v1.Msg/DeleteWebhook", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	// CreateWatch registers a new EVM address watch.
	CreateWatch(context.Context, *MsgCreateWatch) (*MsgCreateWatchResponse, error)
	// DeleteWatch removes an existing watch (must be owner).
	DeleteWatch(context.Context, *MsgDeleteWatch) (*MsgDeleteWatchResponse, error)
	// CreateWebhook registers a new webhook delivery endpoint.
	CreateWebhook(context.Context, *MsgCreateWebhook) (*MsgCreateWebhookResponse, error)
	// DeleteWebhook removes an existing webhook (must be owner).
	DeleteWebhook(context.Context, *MsgDeleteWebhook) (*MsgDeleteWebhookResponse, error)
	// SubmitEvent is called by feeders to record an external chain event.
	SubmitEvent(context.Context, *MsgSubmitEvent) (*MsgSubmitEventResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) CreateWatch(ctx context.Context, req *MsgCreateWatch) (*MsgCreateWatchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateWatch not implemented")
}
func (*UnimplementedMsgServer) DeleteWatch(ctx context.Context, req *MsgDeleteWatch) (*MsgDeleteWatchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteWatch not implemented")
}
func (*UnimplementedMsgServer) CreateWebhook(ctx context.Context, req *MsgCreateWebhook) (*MsgCreateWebhookResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateWebhook not implemented")
}
func (*UnimplementedMsgServer) DeleteWebhook(ctx context.Context, req *MsgDeleteWebhook) (*MsgDeleteWebhookResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteWebhook not implemented")
}
func (*UnimplementedMsgServer) SubmitEvent(ctx context.Context, req *MsgSubmitEvent) (*MsgSubmitEventResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitEvent not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_CreateWatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgCreateWatch)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).CreateWatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mehr.v1.Msg/CreateWatch",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).CreateWatch(ctx, req.(*MsgCreateWatch))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_DeleteWatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgDeleteWatch)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).DeleteWatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mehr.v1.Msg/DeleteWatch",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).DeleteWatch(ctx, req.(*MsgDeleteWatch))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_CreateWebhook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgCreateWebhook)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).CreateWebhook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mehr.v1.Msg/CreateWebhook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).CreateWebhook(ctx, req.(*MsgCreateWebhook))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_DeleteWebhook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgDeleteWebhook)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).DeleteWebhook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mehr.v1.Msg/DeleteWebhook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).DeleteWebhook(ctx, req.(*MsgDeleteWebhook))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_SubmitEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgSubmitEvent)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).SubmitEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mehr.v1.Msg/SubmitEvent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).SubmitEvent(ctx, req.(*MsgSubmitEvent))
	}
	return interceptor(ctx, in, info, handler)
}

var Msg_serviceDesc = _Msg_serviceDesc
var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "mehr.v1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateWatch",
			Handler:    _Msg_CreateWatch_Handler,
		},
		{
			MethodName: "DeleteWatch",
			Handler:    _Msg_DeleteWatch_Handler,
		},
		{
			MethodName: "CreateWebhook",
			Handler:    _Msg_CreateWebhook_Handler,
		},
		{
			MethodName: "DeleteWebhook",
			Handler:    _Msg_DeleteWebhook_Handler,
		},
		{
			MethodName: "SubmitEvent",
			Handler:    _Msg_SubmitEvent_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mehr/v1/tx.proto",
}

func (m *MsgCreateWatch) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreateWatch) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreateWatch) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Label) > 0 {
		i -= len(m.Label)
		copy(dAtA[i:], m.Label)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Label)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Network) > 0 {
		i -= len(m.Network)
		copy(dAtA[i:], m.Network)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Network)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgCreateWatchResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreateWatchResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreateWatchResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Watch != nil {
		{
			size, err := m.Watch.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTx(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgDeleteWatch) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgDeleteWatch) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgDeleteWatch) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.WatchId != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.WatchId))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgDeleteWatchResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgDeleteWatchResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgDeleteWatchResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgCreateWebhook) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreateWebhook) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreateWebhook) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.SecretHash) > 0 {
		i -= len(m.SecretHash)
		copy(dAtA[i:], m.SecretHash)
		i = encodeVarintTx(dAtA, i, uint64(len(m.SecretHash)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Url) > 0 {
		i -= len(m.Url)
		copy(dAtA[i:], m.Url)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Url)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgCreateWebhookResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreateWebhookResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreateWebhookResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Webhook != nil {
		{
			size, err := m.Webhook.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTx(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgDeleteWebhook) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgDeleteWebhook) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgDeleteWebhook) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.WebhookId != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.WebhookId))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgDeleteWebhookResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgDeleteWebhookResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgDeleteWebhookResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgCreateWatch) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Network)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Label)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgCreateWatchResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Watch != nil {
		l = m.Watch.Size()
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgDeleteWatch) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.WatchId != 0 {
		n += 1 + sovTx(uint64(m.WatchId))
	}
	return n
}

func (m *MsgDeleteWatchResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgCreateWebhook) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Url)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.SecretHash)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgCreateWebhookResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Webhook != nil {
		l = m.Webhook.Size()
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgDeleteWebhook) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.WebhookId != 0 {
		n += 1 + sovTx(uint64(m.WebhookId))
	}
	return n
}

func (m *MsgDeleteWebhookResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgCreateWatch) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreateWatch: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreateWatch: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Network", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Network = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Label", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Label = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCreateWatchResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreateWatchResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreateWatchResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Watch", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Watch == nil {
				m.Watch = &Watch{}
			}
			if err := m.Watch.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgDeleteWatch) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgDeleteWatch: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgDeleteWatch: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field WatchId", wireType)
			}
			m.WatchId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.WatchId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgDeleteWatchResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgDeleteWatchResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgDeleteWatchResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCreateWebhook) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreateWebhook: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreateWebhook: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Url", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Url = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SecretHash", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SecretHash = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCreateWebhookResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreateWebhookResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreateWebhookResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Webhook", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Webhook == nil {
				m.Webhook = &Webhook{}
			}
			if err := m.Webhook.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgDeleteWebhook) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgDeleteWebhook: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgDeleteWebhook: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field WebhookId", wireType)
			}
			m.WebhookId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.WebhookId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgDeleteWebhookResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgDeleteWebhookResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgDeleteWebhookResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
